-- Seed MCQ quizzes for SQL, Java, and Python
-- Run this against the gmtech MySQL database after the quizzes/questions tables exist.

INSERT INTO quizzes (title, description, time_limit, status, max_attempts) VALUES ('SQL Assessment', 'SQL fundamentals, joins, aggregation, normalization, transactions, and query reasoning.', 30, 'active', 1);
SET @quiz_id = LAST_INSERT_ID();
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'Which SQL clause filters grouped rows after aggregation?', 'WHERE', 'HAVING', 'GROUP BY', 'ORDER BY', 2);
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'Which join returns all rows from the left table and matching rows from the right table?', 'INNER JOIN', 'LEFT JOIN', 'RIGHT JOIN', 'CROSS JOIN', 2);
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'What does COUNT(*) return?', 'Only non-null values in one column', 'Total rows in the result set', 'Distinct rows only', 'Number of tables', 2);
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'Which command removes all rows from a table while usually keeping its structure?', 'DROP', 'TRUNCATE', 'ALTER', 'RENAME', 2);
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'Which normal form removes partial dependency on part of a composite key?', '1NF', '2NF', '3NF', 'BCNF', 2);
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'What is the main purpose of an index?', 'Encrypt data', 'Improve lookup speed', 'Increase table size', 'Prevent all duplicates', 2);
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'Which SQL keyword removes duplicate rows from a result?', 'UNIQUE', 'DISTINCT', 'ONLY', 'GROUP', 2);
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'What does a primary key guarantee?', 'Nullable values', 'Unique non-null row identification', 'Only text values', 'Automatic sorting', 2);
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'Which aggregate function ignores NULL values?', 'COUNT(column)', 'COUNT(*)', 'SELECT *', 'ORDER BY', 1);
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'Which operator checks whether a value is within a set of values?', 'LIKE', 'IN', 'BETWEEN', 'EXISTS', 2);
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'Which clause is evaluated logically before SELECT?', 'ORDER BY', 'WHERE', 'LIMIT', 'Alias display', 2);
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'What does ACID durability mean?', 'Transactions run quickly', 'Committed data survives failures', 'Data is always duplicated', 'Queries are cached', 2);
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'Which statement changes existing table rows?', 'INSERT', 'UPDATE', 'CREATE', 'GRANT', 2);
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'Which constraint enforces a relationship to a key in another table?', 'CHECK', 'DEFAULT', 'FOREIGN KEY', 'NOT NULL', 3);
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'Which query finds rows where email is missing?', 'email = NULL', 'email IS NULL', 'email == NULL', 'email LIKE NULL', 2);
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'What is a correlated subquery?', 'A subquery that references the outer query', 'A query with no WHERE clause', 'A query using only one table', 'A query that always returns one row', 1);
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'Which isolation issue happens when the same query returns different row sets during a transaction?', 'Dirty read', 'Lost update', 'Phantom read', 'Syntax error', 3);
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'Which clause sorts query results?', 'SORT BY', 'ORDER BY', 'GROUP SORT', 'RANK BY', 2);
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'What does UNION do by default?', 'Combines results and removes duplicates', 'Combines results and keeps duplicates', 'Joins columns horizontally', 'Deletes duplicate table rows', 1);
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'Which function returns the largest value in a group?', 'TOP', 'MAX', 'LARGEST', 'HIGH', 2);

INSERT INTO quizzes (title, description, time_limit, status, max_attempts) VALUES ('Java Assessment', 'Java syntax, OOP, collections, exceptions, streams, concurrency, and problem solving.', 30, 'active', 1);
SET @quiz_id = LAST_INSERT_ID();
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'Which keyword is used to inherit a class in Java?', 'implements', 'extends', 'inherits', 'super', 2);
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'Which collection does not allow duplicate elements?', 'List', 'Set', 'Queue', 'ArrayList', 2);
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'What is the default value of an int instance variable?', 'null', '0', '1', 'undefined', 2);
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'Which method is the entry point of a standard Java application?', 'start()', 'main()', 'run()', 'init()', 2);
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'Which keyword prevents a class from being inherited?', 'static', 'final', 'private', 'sealedonly', 2);
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'Which exception type is checked at compile time?', 'NullPointerException', 'IOException', 'ArithmeticException', 'ArrayIndexOutOfBoundsException', 2);
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'What does JVM stand for?', 'Java Variable Machine', 'Java Virtual Machine', 'Java Verified Method', 'Joint Virtual Module', 2);
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'Which operator compares object references?', 'equals()', '==', 'compareTo()', 'instanceof only', 2);
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'Which interface is commonly used for sorting objects naturally?', 'Runnable', 'Comparable', 'Serializable', 'Cloneable', 2);
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'Which access modifier is most restrictive?', 'public', 'protected', 'private', 'default', 3);
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'What is method overloading?', 'Same method name with different parameters', 'Changing superclass method behavior', 'Using private methods only', 'Running multiple threads', 1);
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'Which block always runs after try/catch unless the JVM exits?', 'throw', 'finally', 'final', 'default', 2);
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'Which class is immutable?', 'String', 'StringBuilder', 'ArrayList', 'HashMap', 1);
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'Which package contains ArrayList?', 'java.io', 'java.util', 'java.net', 'java.sql only', 2);
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'Which keyword creates an object?', 'class', 'new', 'object', 'make', 2);
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'What does static mean for a variable?', 'Belongs to the class', 'Belongs only to one object', 'Cannot change ever', 'Is stored in a file', 1);
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'Which stream operation transforms each element?', 'filter', 'map', 'collect', 'sorted only', 2);
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'Which interface represents a task run by a thread?', 'Runnable', 'Iterable', 'Comparator', 'AutoCloseable', 1);
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'What is encapsulation?', 'Hiding data behind methods', 'Copying objects', 'Compiling bytecode', 'Deleting unused methods', 1);
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'Which keyword is used to handle an exception?', 'catch', 'error', 'rescue', 'handle', 1);

INSERT INTO quizzes (title, description, time_limit, status, max_attempts) VALUES ('Python Assessment', 'Python syntax, data structures, functions, files, exceptions, OOP, and problem solving.', 30, 'active', 1);
SET @quiz_id = LAST_INSERT_ID();
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'Which data type is immutable in Python?', 'list', 'dict', 'set', 'tuple', 4);
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'Which keyword defines a function?', 'func', 'def', 'function', 'lambda only', 2);
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'What is the output type of input()?', 'int', 'str', 'float', 'bool', 2);
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'Which structure stores key-value pairs?', 'list', 'tuple', 'dict', 'set', 3);
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'Which statement handles exceptions?', 'try/except', 'if/else', 'for/else only', 'catch/finally only', 1);
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'What does len([1, 2, 3]) return?', '2', '3', '4', 'Error', 2);
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'Which operator performs floor division?', '/', '//', '%', '**', 2);
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'Which method adds an item to the end of a list?', 'add', 'append', 'insertEnd', 'push', 2);
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'What does range(3) generate?', '1,2,3', '0,1,2', '0,1,2,3', '3 only', 2);
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'Which keyword creates a class?', 'object', 'class', 'struct', 'typeclass', 2);
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'Which expression creates a set?', '[]', '{} with key:value', '{1, 2, 3}', '()', 3);
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'What does PEP 8 define?', 'Database rules', 'Python style guide', 'Compiler internals', 'Package installer', 2);
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'Which file mode opens a file for appending?', 'r', 'w', 'a', 'x only', 3);
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'What is list comprehension used for?', 'Creating lists concisely', 'Deleting variables', 'Importing modules', 'Handling threads only', 1);
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'Which module is commonly used for JSON parsing?', 'csv', 'json', 'pickle only', 'os', 2);
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'What does is compare?', 'Object identity', 'Only numeric equality', 'String length', 'Dictionary keys', 1);
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'Which keyword exits a loop immediately?', 'skip', 'break', 'continue', 'pass', 2);
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'Which keyword skips to the next loop iteration?', 'break', 'continue', 'pass', 'return', 2);
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'What does *args collect?', 'Keyword arguments', 'Variable positional arguments', 'Class attributes', 'Environment variables', 2);
INSERT INTO questions (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES (@quiz_id, 'Which method converts a string to lowercase?', 'lower()', 'down()', 'casefold only', 'small()', 1);
